// Generated by npm run images. Edit the source JPGs, then regenerate.
window.OPENING_IMAGES = [
  {
    "id": "01",
    "src": "assets/opening/frames/01-1600-bffa7b263d.webp",
    "srcset": "assets/opening/frames/01-480-4ff597cf5f.webp 480w, assets/opening/frames/01-768-32b972d6aa.webp 768w, assets/opening/frames/01-1024-2442ce091a.webp 1024w, assets/opening/frames/01-1600-bffa7b263d.webp 1600w",
    "mobileSrcset": "assets/opening/frames/01-480-4ff597cf5f.webp 480w, assets/opening/frames/01-768-32b972d6aa.webp 768w, assets/opening/frames/01-1024-2442ce091a.webp 1024w",
    "blur": "assets/opening/frames/01-blur-ebc214f768.webp",
    "width": 1600,
    "height": 1067
  },
  {
    "id": "02",
    "src": "assets/opening/frames/02-1600-a4e9da9787.webp",
    "srcset": "assets/opening/frames/02-480-ede532d8d7.webp 480w, assets/opening/frames/02-768-c4905a3cce.webp 768w, assets/opening/frames/02-1024-43b7c9f139.webp 1024w, assets/opening/frames/02-1600-a4e9da9787.webp 1600w",
    "mobileSrcset": "assets/opening/frames/02-480-ede532d8d7.webp 480w, assets/opening/frames/02-768-c4905a3cce.webp 768w, assets/opening/frames/02-1024-43b7c9f139.webp 1024w",
    "blur": "assets/opening/frames/02-blur-44ef7dfbb1.webp",
    "width": 1600,
    "height": 1067
  },
  {
    "id": "03",
    "src": "assets/opening/frames/03-1600-f8764e22b6.webp",
    "srcset": "assets/opening/frames/03-480-2eb9ebd018.webp 480w, assets/opening/frames/03-768-b0e8de7415.webp 768w, assets/opening/frames/03-1024-97988b1e2a.webp 1024w, assets/opening/frames/03-1600-f8764e22b6.webp 1600w",
    "mobileSrcset": "assets/opening/frames/03-480-2eb9ebd018.webp 480w, assets/opening/frames/03-768-b0e8de7415.webp 768w, assets/opening/frames/03-1024-97988b1e2a.webp 1024w",
    "blur": "assets/opening/frames/03-blur-54d1970a64.webp",
    "width": 1600,
    "height": 1067
  },
  {
    "id": "04",
    "src": "assets/opening/frames/04-1600-89fda48b65.webp",
    "srcset": "assets/opening/frames/04-480-a36c965826.webp 480w, assets/opening/frames/04-768-762e0d9565.webp 768w, assets/opening/frames/04-1024-a487cf094f.webp 1024w, assets/opening/frames/04-1600-89fda48b65.webp 1600w",
    "mobileSrcset": "assets/opening/frames/04-480-a36c965826.webp 480w, assets/opening/frames/04-768-762e0d9565.webp 768w, assets/opening/frames/04-1024-a487cf094f.webp 1024w",
    "blur": "assets/opening/frames/04-blur-90eb08c228.webp",
    "width": 1600,
    "height": 1067
  },
  {
    "id": "05",
    "src": "assets/opening/frames/05-1600-ff802e9096.webp",
    "srcset": "assets/opening/frames/05-480-ba0ba44b5d.webp 480w, assets/opening/frames/05-768-70a48d5d90.webp 768w, assets/opening/frames/05-1024-50b5282240.webp 1024w, assets/opening/frames/05-1600-ff802e9096.webp 1600w",
    "mobileSrcset": "assets/opening/frames/05-480-ba0ba44b5d.webp 480w, assets/opening/frames/05-768-70a48d5d90.webp 768w, assets/opening/frames/05-1024-50b5282240.webp 1024w",
    "blur": "assets/opening/frames/05-blur-e9f6202afc.webp",
    "width": 1600,
    "height": 1067
  },
  {
    "id": "06",
    "src": "assets/opening/frames/06-1600-12b1fc7dbb.webp",
    "srcset": "assets/opening/frames/06-480-ec710b5782.webp 480w, assets/opening/frames/06-768-2610ff9a95.webp 768w, assets/opening/frames/06-1024-5c6854699e.webp 1024w, assets/opening/frames/06-1600-12b1fc7dbb.webp 1600w",
    "mobileSrcset": "assets/opening/frames/06-480-ec710b5782.webp 480w, assets/opening/frames/06-768-2610ff9a95.webp 768w, assets/opening/frames/06-1024-5c6854699e.webp 1024w",
    "blur": "assets/opening/frames/06-blur-cad7e28948.webp",
    "width": 1600,
    "height": 1067
  },
  {
    "id": "07",
    "src": "assets/opening/frames/07-1600-a6d9e40982.webp",
    "srcset": "assets/opening/frames/07-480-daaeb46bec.webp 480w, assets/opening/frames/07-768-fb7c96ae02.webp 768w, assets/opening/frames/07-1024-e36ebb73d6.webp 1024w, assets/opening/frames/07-1600-a6d9e40982.webp 1600w",
    "mobileSrcset": "assets/opening/frames/07-480-daaeb46bec.webp 480w, assets/opening/frames/07-768-fb7c96ae02.webp 768w, assets/opening/frames/07-1024-e36ebb73d6.webp 1024w",
    "blur": "assets/opening/frames/07-blur-2faf9c66a1.webp",
    "width": 1600,
    "height": 1067
  },
  {
    "id": "08",
    "src": "assets/opening/frames/08-1600-d4474ead52.webp",
    "srcset": "assets/opening/frames/08-480-95afebf51b.webp 480w, assets/opening/frames/08-768-d14198a588.webp 768w, assets/opening/frames/08-1024-5422d36ebd.webp 1024w, assets/opening/frames/08-1600-d4474ead52.webp 1600w",
    "mobileSrcset": "assets/opening/frames/08-480-95afebf51b.webp 480w, assets/opening/frames/08-768-d14198a588.webp 768w, assets/opening/frames/08-1024-5422d36ebd.webp 1024w",
    "blur": "assets/opening/frames/08-blur-0e2681af27.webp",
    "width": 1600,
    "height": 1067
  },
  {
    "id": "09",
    "src": "assets/opening/frames/09-1600-9bf7600c07.webp",
    "srcset": "assets/opening/frames/09-480-781751c0bd.webp 480w, assets/opening/frames/09-768-d8d50f8af1.webp 768w, assets/opening/frames/09-1024-ce382d568d.webp 1024w, assets/opening/frames/09-1600-9bf7600c07.webp 1600w",
    "mobileSrcset": "assets/opening/frames/09-480-781751c0bd.webp 480w, assets/opening/frames/09-768-d8d50f8af1.webp 768w, assets/opening/frames/09-1024-ce382d568d.webp 1024w",
    "blur": "assets/opening/frames/09-blur-a5527cda50.webp",
    "width": 1600,
    "height": 1067
  },
  {
    "id": "10",
    "src": "assets/opening/frames/10-1600-9ab5008a4e.webp",
    "srcset": "assets/opening/frames/10-480-27221efe9b.webp 480w, assets/opening/frames/10-768-38e8301db1.webp 768w, assets/opening/frames/10-1024-a8b5529bbb.webp 1024w, assets/opening/frames/10-1600-9ab5008a4e.webp 1600w",
    "mobileSrcset": "assets/opening/frames/10-480-27221efe9b.webp 480w, assets/opening/frames/10-768-38e8301db1.webp 768w, assets/opening/frames/10-1024-a8b5529bbb.webp 1024w",
    "blur": "assets/opening/frames/10-blur-5681be7ce4.webp",
    "width": 1600,
    "height": 1067
  },
  {
    "id": "11",
    "src": "assets/opening/frames/11-1600-9955d7fb39.webp",
    "srcset": "assets/opening/frames/11-480-4e5973985a.webp 480w, assets/opening/frames/11-768-27492e20a1.webp 768w, assets/opening/frames/11-1024-b56be29142.webp 1024w, assets/opening/frames/11-1600-9955d7fb39.webp 1600w",
    "mobileSrcset": "assets/opening/frames/11-480-4e5973985a.webp 480w, assets/opening/frames/11-768-27492e20a1.webp 768w, assets/opening/frames/11-1024-b56be29142.webp 1024w",
    "blur": "assets/opening/frames/11-blur-46c4a34b9c.webp",
    "width": 1600,
    "height": 1067
  },
  {
    "id": "12",
    "src": "assets/opening/frames/12-1600-f802bc73d1.webp",
    "srcset": "assets/opening/frames/12-480-bfc83edee4.webp 480w, assets/opening/frames/12-768-815fca0b23.webp 768w, assets/opening/frames/12-1024-578a41c228.webp 1024w, assets/opening/frames/12-1600-f802bc73d1.webp 1600w",
    "mobileSrcset": "assets/opening/frames/12-480-bfc83edee4.webp 480w, assets/opening/frames/12-768-815fca0b23.webp 768w, assets/opening/frames/12-1024-578a41c228.webp 1024w",
    "blur": "assets/opening/frames/12-blur-97a983e38b.webp",
    "width": 1600,
    "height": 1067
  },
  {
    "id": "13",
    "src": "assets/opening/frames/13-1600-7d5de52cfc.webp",
    "srcset": "assets/opening/frames/13-480-07f9c7b385.webp 480w, assets/opening/frames/13-768-e876ee764e.webp 768w, assets/opening/frames/13-1024-ff3d906726.webp 1024w, assets/opening/frames/13-1600-7d5de52cfc.webp 1600w",
    "mobileSrcset": "assets/opening/frames/13-480-07f9c7b385.webp 480w, assets/opening/frames/13-768-e876ee764e.webp 768w, assets/opening/frames/13-1024-ff3d906726.webp 1024w",
    "blur": "assets/opening/frames/13-blur-7b4bce5613.webp",
    "width": 1600,
    "height": 1067
  },
  {
    "id": "14",
    "src": "assets/opening/frames/14-1600-63b29a330f.webp",
    "srcset": "assets/opening/frames/14-480-8ecfbbb764.webp 480w, assets/opening/frames/14-768-7f22b8aaa5.webp 768w, assets/opening/frames/14-1024-f25cf6c0fd.webp 1024w, assets/opening/frames/14-1600-63b29a330f.webp 1600w",
    "mobileSrcset": "assets/opening/frames/14-480-8ecfbbb764.webp 480w, assets/opening/frames/14-768-7f22b8aaa5.webp 768w, assets/opening/frames/14-1024-f25cf6c0fd.webp 1024w",
    "blur": "assets/opening/frames/14-blur-11ee57a1e3.webp",
    "width": 1600,
    "height": 1067
  },
  {
    "id": "15",
    "src": "assets/opening/frames/15-1600-87d973d107.webp",
    "srcset": "assets/opening/frames/15-480-85f7f1633d.webp 480w, assets/opening/frames/15-768-692a5b8793.webp 768w, assets/opening/frames/15-1024-7e326d1783.webp 1024w, assets/opening/frames/15-1600-87d973d107.webp 1600w",
    "mobileSrcset": "assets/opening/frames/15-480-85f7f1633d.webp 480w, assets/opening/frames/15-768-692a5b8793.webp 768w, assets/opening/frames/15-1024-7e326d1783.webp 1024w",
    "blur": "assets/opening/frames/15-blur-2d0a6f72eb.webp",
    "width": 1600,
    "height": 1067
  }
];
